#!/bin/bash
#    if ["$1" == "-c"]
#   then
#    # this part gonna be script for runing some gui to provide 
#    # the custom test for the txt and the how much file that creat in secend 
#    # arg like -/
#    # tng -c 10




#    exit 0
#fi

# we can use sed -i '1i text massage ' filename for more speed 

filename=$1
editor="$(< /etc/tng/e.zngdm)"
name="$(< /etc/tng/n.zngdm)"
touch "$filename"
if [[ $1 == *.py || $1 == *.pyw || $1 == *.pyc || $1 == *.pyd || $1 == *.pyo || $1 == *.rb || $1 == *.rbw || $1 == *.rbx || $1 == *.rbo || $1 == *.gy ]]; then
    echo "# editor = ${editor}" >> "$filename"
    echo "# Created By ${name}" >> "$filename"
    echo "# $(date +"%Y.%m.%d %H:%M")" >> "$filename"
elif [[ $1 == *.cc || $1 == *.cpp || $1 == *.cxx || $1 == *.c || $1 == *.cs || $1 == *.csharp || $1 == *.go || $1 == *.gopkg || $1 == *.mod || $1 == *.java || $1 == *.class || $1 == *.js || $1 == *.jsx || $1 == *.jsm || $1 == *.mjs || $1 == *.node || $1 == *.ts || $1 == *.tsx || $1 == *.d.ts || $1 == *.cts || $1 == *.php || $1 == *.php3 || $1 == *.php4 || $1 == *.php5 || $1 == *.phtml || $1 == *.inc || $1 == *.rs || $1 == *.rlib || $1 == *.toml || $1 == *.swift || $1 == *.swiftmodule || $1 == *.swiftinterface || $1 == *.swiftdoc ]]; then
    echo "/// editor = ${editor}" >> "$filename"
    echo "/// Created By ${name}" >> "$filename"
    echo "/// $(date +"%Y.%m.%d %H:%M")" >> "$filename"
elif [[ $1 == *.lua || $1 == *.luac || $1 == *.moon || $1 == *.wlua || $1 == *.nse ]]; then
    echo "-- editor = ${editor}" >> "$filename"
    echo "-- Created By ${name}" >> "$filename"
    echo "-- $(date +"%Y.%m.%d %H:%M")" >> "$filename"
elif [[ $1 == *.sh ]]; then
    echo "#!/bin/bash" >> "$filename"
    echo "# editor = ${editor}" >> "$filename"
    echo "# Created By ${name}" >> "$filename"
    echo "# $(date +"%Y.%m.%d %H:%M")" >> "$filename"
elif [[ $1 == *csd ]]; then
    echo "; editor = ${editor}" >> "$filename"
    echo "; Created By ${name}" >> "$filename"
    echo "; $(date +"%Y.%m.%d %H:%M")" >> "$filename"
    echo "<CsoundSynthesizer>" >> "$filename"
    echo "<CsOptions>" >> "$filename"
    echo "</CsOptions>" >> "$filename"
    echo "<CsInstruments>" >> "$filename"
    echo "</CsInstruments>" >> "$filename"
    echo "<CsScore>" >> "$filename"
    echo "</CsScore>" >> "$filename"
    echo "</CsoundSynthesizer>" >> "$filename"
fi

exit 0
