# tng config example

# tng config syntax rules
# For variable with bool type you can use <YES> or <NO> instead of <true> or <false>
# You can't use non-absolute path for addressing path
# Use """ for more then one line string

		[cpp, c, cc, hpp, h]


####################################
############## Policy ##############


# First we have buffer setup.
#   define buffer writted with comment 
#	define comment element's
#   define license path
#   
# Use comment for all tng generated text for files
comment = YES
comment_style = block # block or line

# Each element of comment for multi-line comment or liner comment
# In this example we have
#
#	// Line
#
#	/*
#	 * Non-liner or Block comment
#	 */
# 
line_prefix = "//"
block_header = "/*"
block_line_prefix = " * "
block_footer = " */"

# Include license file in project
include_license = YES

# Locate license path
license_path = "/home/exampleUserName/license-file/"
# TODO: use PWD in here
# -> license_path = "PWD/license/"

# Pre configed
include_license_before_header = YES
space_between_header_footer = 4
overwrite_existing_file = NO # tng defualt in no 


####################################
############## Layout ##############


header_text = """
Project by : Ilia Abolghasemy (aka: gfaerny, Iliya Abolghasemi)
"""

footer_text="""
Copyright by Ilia Abolghasemy
"""

# TODO: Did we have to write modifie analyzer for tng to undrestand last time config got updated and-
# time file gotted update so we can rewrite the generated buffer or not

		[GLOBAL]
