# Gfaerny
# Example and Default tng config
# Each element
#            
#           liner comment
#            |
#                  first part of multi-liner comment
#                   |
#                       first charecter of each multi-liner comment section
#                        | (you can leave this paramert blank) 
#                              end of multi-comment
#                               |
#           use
#            |
#  so here we can undrestand we can't able to use *.-> file
#  like
#  [X] cpp , -> , mp -> "//" 

cpp, c, css -> //, /*, *, */

ex -> // , /* , * , */
# single_line_comment
# multi_line_comment
#
# /*
#  * hi hi 
#  */
# // hi

use_newline_for_multi-liner=true

#  // Hi this is line comment
#
#  /* 
#   * Hi this is multi-line 
#   */
#
add_text="hi"
license_dir_path=/path/to/directory/ , /path/license2/ , /commen-license-path/
