#!/bin/bash
#welcome to tng
#[tng] is linux CLI-App That Make you Sing your first Line's code
echo " HI this is Tng installer.Just Know You Have To Run TngInstaller In Root User"
echo -e "\033[91m [Press Enter To Continue...] \033[0m"
read -n1
echo " And You Have Use it In Root User"
echo -e "\033[91m [Press Enter To Continue...] \033[0m"
read -n1
echo " Please Enter The Name Of Editor That You Use"
read -p "Editor Name: " editor
echo 
echo " OK!!! Yor Editor Is ${editor} Now Enter Your Name:‌"
read -p "Name: " name
echo " ${name} Done"
echo " In The End...If You Want To Make File with incode.py,.cpp,.c,.go,.java,.js,.cs and..."
echo -e "\033[91m [Press Enter To Continue...] \033[0m"
read -n1
echo "Your Comment Gonna Write With Your special File Extension"
cat srcc.txt
echo -e "\033[91m [If You Understand Press Enter To Continue...] \033[0m"
read -n1
mkdir /etc/tng/
touch /etc/tng/e.zngdm
touch /etc/tng/n.zngdm
echo "$editor" >"/etc/tng/e.zngdm"
echo "$name" >"/etc/tng/n.zngdm"
echo -e "\033[91m [the information copied...] \033[0m"
mv tng /bin/

echo  "TNG Is Ready TO Use type = tng file.example"‌
